name: deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yaml
      - agent.yaml
      - Dockerfile

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Release Grafana Agent
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: grafana-agent
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_heroku_process_type: worker
        env:
          HD_GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
