name: deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yaml
      - agent.yaml
      - Dockerfile

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - run: curl https://cli-assets.heroku.com/install.sh | sh